Repository fazer-ai/chatwoot, pull requests merged in 2025-05, with the labels that each got.

#34 fix: ignore protocolMessages
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, approved for merge

#36 feat: mark recorded audio messages
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/builders/messages/message_builder_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, review needed

#39 feat: toggle typing status on channel provider
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/public/api/v1/inboxes/conversations_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/components/ResizableTextArea.vue
  app/listeners/channel_listener.rb
  app/models/channel/whatsapp.rb
  app/services/conversations/typing_status_manager.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  lib/events/types.rb
  spec/listeners/channel_listener_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
  swagger/paths/public/inboxes/conversations/toggle_typing.yml
  swagger/swagger.json
Labels: enhancement

#35 feat: add flag to edited messages and content history tracking
  app/models/message.rb
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, approved for merge

#43 feat: mark message as read
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/listeners/channel_listener.rb
  app/models/channel/whatsapp.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  lib/events/types.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/listeners/channel_listener_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#44 feat: use message is unsupported content attribute
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#48 feat: Baileys-API get media using CDN
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#49 feat: mark unread conversations
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/listeners/channel_listener.rb
  app/models/channel/whatsapp.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  lib/events/types.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/listeners/channel_listener_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#52 feat: update message status and last seen timestamps
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, approved for merge

#51 fix(baileys): race condition send_message/incoming message
  app/helpers/baileys_helper.rb
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  spec/helpers/baileys_helper_spec.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: bug, approved for merge

#59 Fix: Incoming Message Baileys Service Specs
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: bug, approved for merge
