Repository fazer-ai/chatwoot, pull requests merged in 2025-04, with the labels that each got.

#11 feat: add Resend email delivery method and configuration
  .env.example
  Gemfile
  Gemfile.lock
  app/views/devise/mailer/reset_password_instructions.html.erb
  config/initializers/mailer.rb
  config/initializers/resend.rb
  lib/mail/resend_provider.rb
  spec/lib/mail/resend_provider_spec.rb
Labels: enhancement

#9 fix: handle extended text message type of incoming message upsert
  app/javascript/dashboard/composables/spec/useUISettings.spec.js
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, question, approved for merge

#13 fix: new contact without push name
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: bug, approved for merge

#21 feat: process webhook whatsapp await response
  app/controllers/webhooks/whatsapp_controller.rb
  spec/controllers/webhooks/whatsapp_controller_spec.rb
Labels: enhancement, approved for merge

#20 feat: add message update processing in IncomingMessageBaileysService
  app/controllers/webhooks/whatsapp_controller.rb
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/controllers/webhooks/whatsapp_controller_spec.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, approved for merge

#23 fix: allow composing message when using baileys inbox
  app/javascript/dashboard/components-next/NewConversation/components/ActionButtons.vue
  app/javascript/dashboard/components-next/NewConversation/components/ComposeNewConversationForm.vue
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
Labels: enhancement, approved for merge

#30 chore: change baileys contact name preferences
  app/services/whatsapp/incoming_message_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#28 feat: baileys support to send attachments
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#27 feat: baileys unsupported message alert
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  config/locales/en.yml
  config/locales/pt_BR.yml
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#29 fix: try to disconnect baileys before destroy inbox
  app/models/channel/whatsapp.rb
  spec/models/channel/whatsapp_spec.rb
Labels: enhancement, approved for merge

#26 feat: process Baileys-API images in message.upsert event
  app/controllers/webhooks/whatsapp_controller.rb
  app/models/channel/whatsapp.rb
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  config/locales/en.yml
  config/locales/pt_BR.yml
  spec/models/attachment_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#32 fix: baileys send message with jid
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge

#33 feat: baileys messages reactions
  app/javascript/dashboard/components/widgets/forms/Input.vue
  app/models/message.rb
  app/services/whatsapp/incoming_message_baileys_service.rb
  app/services/whatsapp/providers/whatsapp_baileys_service.rb
  spec/services/whatsapp/incoming_message_baileys_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_baileys_service_spec.rb
Labels: enhancement, approved for merge
